export const AppointmentStatus = {
    PENDING_PAYMENT : 'PENDING PAYMENT',
    PAYMENT_FAILED : 'PAYMENT FAILED',
    PENDING_CONFIRMATION : 'PENDING CONFIRMATION',
    CONFIRMED : 'CONFIRMED',
    SERVICE_DONE : 'SERVICE DONE',
    CUSTOMER_NO_SHOW : 'CUSTOMER NO SHOW',
    PENDING_REFUND : 'PENDING REFUND',
    CANCELLED_BY_ADMIN : 'CANCELLED BY ADMIN',
    CANCELLED_BY_CUSTOMER : 'CANCELLED BY CUSTOMER',
  }